config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  root 'static_pages#landing_page'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :new, :create]

  post 'payments/create'

   

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true
	has_many :orders
	has_many :comments

	def average_rating
		comments.average(:rating).to_f
	end

	def compare_rating(average_rating)
		$redis.zadd("average_ratings", average_rating, self.id)
	end

	def rank
		$redis.zrevrank("average_ratings", self.id) + 1
	end

	def best_product
		$redis.zscore("average_ratings", self.id).to_i
	end

	def self.top_3
		$redis.zrevrange("average_ratings", 0, 2).map{|id| Product.find(id)}
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
        if Rails.env.production?
          @products = Product.where("name ilike ?", "%#{search_term}%")
        else    
          @products = Product.where("name LIKE ?", "%#{search_term}%")
        end
    else
      @products = Product.all
    end  
    respond_with @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.paginate(:page => params[:page])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

	def cache_key_for_products
		count = Product.count
		max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"products/all-#{count}--#{max_updated_at}"
	end

end

app/views/products/_comments.html.erb
<div class="product-reviews">
	<% @comments.each do |comment| %>
		<div class="row">
			<hr>
			<p>
				Reviewed by <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
				<% if signed_in? && current_user.admin? %>
					<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
			</p>
       <div class="rated" data-score="<%= comment.rating %>"></div>
      <p><%= comment.body %></p>
		</div>
	<% end %>
</div>

<%= will_paginate @comments %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="field form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :price %><br>
        <%= f.text_field :price, :class => 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, :class => 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :image_url %><br>
        <%= f.text_field :image_url, :class => 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :color %><br>
        <%= f.text_field :color, :class => 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit(class: 'btn btn-default') %>
      </div>
    </div>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
	<h4 class="add-review">Add a Review:</h4>
	<%= form_for([@product, @product.comments.build], remote: true) do |f| %>
		<div class="row">
			<div class="col-md-3">
				<div class="form-group">
					<%= f.label :body, "Comments" %><br>
					<%= f.text_area :body, :class => 'form-control' %>
				</div>
				<div class="form-group">
					<div class="rating"></div>
				</div>
				<div class="actions">
        <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
            Create Review
        <% end %>
      </div>
		  </div>
		</div>
	<% end %>
<% end %>

app/views/products/_product.html.erb

  <div class="row">

    <div class="col-md-1 price">
      <h3>$<%= product.price/100 %></h3>
    </div>
    <div class="col-md-4">
      <h3><%= link_to product.name, product %></h3>
    </div>
    
  </div>

  <div class="row">
    <div class="col-md-3">
      <p><%= product.description %></p>
      <p>Color: <%= product.color %></p>
        <%= link_to 'Edit', edit_product_path(product) %> | 
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <div class="col-md-3 bike-image">
      <%= image_tag(product.image_url, :class => 'img-thumbnail') %>
    </div>
  </div>
  <hr>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1 class="products">Our Products</h1>



	<%= render @products %>


<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
 <div class="row">
    <div class="col-md-1 col-sm-2 col-xs-3 price">
      <h3>$<%= @product.price/100 %></h3>
    </div>
    <div class="col-md-6 col-md-offset-1 col-sm-6 col-sm-offset-1 col-sm-8 col-xs-offset-1">
      <h3><%= @product.name %></h3>
    </div>
  
  
  </div>

  <br>

  <div class="row product-info">
    <div class="col-md-4  col-sm-6">
      <%= image_tag(@product.image_url, width: "350", :class => 'img-zoom', data_zoom_image: @product.image_url) %>
    </div>
    <div class="col-md-3 col-sm-6">
      <p><%= @product.description %></p><br>
      <p><em>Color:</em> <%= @product.color %></p>
      <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div></p>
      <br>
      <%= form_tag "/payments/create" do %>
        <%= render partial: "shared/stripe_checkout_button" %>
        
      <% end %>
    </div>
  </div>

  <hr>

 <%= render 'new_comment' %>

 <%= render 'comments' %>