config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  root 'static_pages#landing_page'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :new, :create]

  post 'payments/create'

   

end

app/views/layouts/_navbar.html.erb
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><%= link_to "Home", root_path %></li>
	        <li><%= link_to "Our Products", products_path %></li>
	      	<li>
	      		<%= form_tag("/products", method: "get", :class => 'navbar-form navbar-left') do %>
	      			<div class="form-group">
								<%= text_field_tag(:q) %>
								<%= button_tag(type: 'submit', class: "btn btn-primary") do %>
									Search
								<% end %>
	    				</div>
	      		<% end %>
	      	</li>
	      </ul>
		
	      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to "Start Your Order", new_order_path %></li>
	        <li><%= link_to "About Us", static_pages_about_path %></li>
	        <li><%= link_to "Contact Us", static_pages_contact_path %></li>
	      	<li>
						<% if user_signed_in? %>
							<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
						<% else %>
							<%= link_to('Login', new_user_session_path) %>
						<% end %>
					</li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firstapp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render "layouts/navbar" %>

	<div class="container">
		
		<div class="row header">
			<div class="col-md-4 col-sm-12">
				<%= image_tag("bike.jpg") %>
			</div>
			<div class="col-md-6 col-sm-12">
				<h1 class="text-center">Welcome to Jersey Shore Bikes</h1>
				<h2 class="text-center">Find the best used bikes on the Shore!</h2>
			</div>
		</div>
	
		<% if notice %>
			<p class="alert notice alert-success" role="alert"><%= notice %></p>
		<% end %>
		<% if alert %>
			<p class="alert alert-danger" role="alert"><%= alert %></p>
		<% end %>

		<%= yield %>

	</div><!-- end container -->

	<br>
	<footer class="footer">
		<div class="container">
			<%= link_to "About Us", static_pages_about_path %>
			<%= link_to "Contact Us", static_pages_contact_path %>  
		</div>
	</footer>
</body>
</html>